version: '3.8'

services:
  frontend_prod:
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    container_name: frontend_prod
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    environment:
      - BACKEND_HOST=backend_prod
    networks:
      - net
  database_prod:
    container_name: database_prod
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_HOST=database
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend_prod:
    container_name: backend_prod
    build:
      context: backend
      dockerfile: ./prod.Dockerfile
    env_file:
      - backend/.env
    environment:
      - DATABASE_HOST=database
    ports:
      - 8000:8000
    volumes:
      - images:/images
    networks:
      - net
    depends_on:
      - database_prod

networks:
  net:

volumes:
  images:
  pgdata:
  