version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    environment:
      - BACKEND_HOST=backend
    volumes:
      # Bind mount volume for live frontend updates while developing
      - ./frontend:/client
    networks:
      - net
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_HOST=database
    networks:
      - net
  backend:
    build:
      context: backend
    env_file:
      - backend/.env
    environment:
      - DATABASE_HOST=database
    ports:
      - 8000:8000
    networks:
      - net
    volumes:
      # Bind mount volume for live backend updates while developing
      - ./backend/src:/app/src
      - ./backend/migration:/app/migration
      - images:/images
    depends_on:
      - database

networks:
  net:

volumes:
  images:
  