//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "faqs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub faq_id: i32,
    pub course_offering_id: i32,
    pub answer: String,
    pub question: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::course_offerings::Entity",
        from = "Column::CourseOfferingId",
        to = "super::course_offerings::Column::CourseOfferingId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CourseOfferings,
}

impl Related<super::course_offerings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseOfferings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
