//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod clusters;
pub mod course_offerings;
pub mod faqs;
pub mod messages;
pub mod queue_tags;
pub mod queue_tutors;
pub mod queues;
pub mod request_images;
pub mod request_status_log;
pub mod request_tags;
pub mod requests;
pub mod sea_orm_active_enums;
pub mod tags;
pub mod tutors;
pub mod users;
