//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "statuses")]
pub enum Statuses {
    #[sea_orm(string_value = "not_found")]
    NotFound,
    #[sea_orm(string_value = "seeing")]
    Seeing,
    #[sea_orm(string_value = "seen")]
    Seen,
    #[sea_orm(string_value = "unseen")]
    Unseen,
}
