//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::requests::Entity> for Entity {
    fn to() -> RelationDef {
        super::request_tags::Relation::Requests.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::request_tags::Relation::Tags.def().rev())
    }
}

impl Related<super::queues::Entity> for Entity {
    fn to() -> RelationDef {
        super::queue_tags::Relation::Queues.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::queue_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
